fix: otlp docs cannot compile.
The bug was introduced since we are compiling grpc files using both tonic and grpcio.

The build logs says:
 thread 'main' panicked at 'Error generating protobuf: Os { code: 30, kind: Other, message: "Read-only file system" }

But we already have compiled files in `proto/grpcio`. Thus ignore this error and print a warning message.

---

Why not use $OUT_DIR? The generated mod file doesn't contain `trace_service_grpc` and `metrics_service_grpc`. Thus, we still need to maintain them in `proto/grpcio`. I'd rather we keep all generated files at the same place