fix: url needs std specified to compile idna
idna dep of url is failing to compile on stable because default_features is false.
std is a default feature that disables the unstable use of error_in_core.

error[E0658]: use of unstable library feature 'error_in_core'
error: could not compile `idna` (lib) due to previous error

https://github.com/rust-lang/rust/issues/103765
https://github.com/servo/rust-url/blob/main/url/Cargo.toml#L35